name: publish_conda

on:
  push:
    branches: [ master ]
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    env: 
      PACKAGE_VERSION: "0.1.0"
    steps:
    - uses: actions/checkout@master
    - name: publish-to-conda
      uses: 3liv/conda-package-publish-action@master
      with:
        subDir: 'conda.recipe'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'all'
        override: true
        dry_run: false
