name: publish_conda

on:
  push:
    branches: [ master ]
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    env: 
      PACKAGE_VERSION: "0.1.0"
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: 'conda.recipe'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'all'
        override: true
        dry_run: true
